### ISSUE TITLE
Block, BG and TR formats for the Metro Area

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/General#38]
@ptatian @lhendey 

For the new website we need formats in MD, VA and WV. Right now we have 6 geographies and corresponding formats (rows 5-10 here: L:\Libraries\General\Doc\Geographic levels.xlsx\Geographic levels.xlsx). 

I think the options are to either:
1) update these geographies to include MD, VA and WV.
2) create 6 new geographies that are these but with all 4 states included and leave the original geographies untouched. 

I think in the past Peter was leaning toward option #2. I'm fine with either. Adding 6 new geographic levels does add another layer of complexity to our system but also doesn't risk messing up anything that's already been created.

**Comment by ptatian** [comment]
@rpitingolo @lhendey Yes, I think option 2 is less likely to cause problems with existing code. Thanks.

**Comment by rpitingolo** [comment]
@ptatian thanks. Can you please close the spreadsheet so I can work in it?
